name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # create an executable Jar with all dependencies
      - name: Create JAR file
        run: ./gradlew shadowJar


      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: micronaut-crud-jar
          path: build/libs/micronaut-crud-*-all.jar
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: micronaut-crud-jar
          path: build/libs

      - name: Run tests
        run: java -jar build/libs/micronaut-crud-*-all.jar