name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull_request_review:
    types: [ submitted ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and test
        run: ./gradlew build # also runs tests

      - name: Set JAR file path
        id: set_jar_path
        run: echo "JAR_PATH=$(ls build/libs/micronaut-crud-*-all.jar)" >> $GITHUB_ENV

      - name: Save JAR path as output
        id: save_jar_output
        run: echo "::set-output name=JAR_PATH::$(ls build/libs/micronaut-crud-*-all.jar)"

      # Upload the shadowJAR file as an artifact (it contains everything needed to run the app)
      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: micronaut-crud-jar
          path: build/libs/micronaut-crud-*-all.jar

  release:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: micronaut-crud-jar
          path: build/libs

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: ${{ github.ref != 'refs/heads/main' }}
          prerelease: false

      - name: List downloaded artifacts
        run: ls -l build/libs

      - name: Echo JAR path
        run: echo ${{ steps.save_jar_output.outputs.JAR_PATH }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.save_jar_output.outputs.JAR_PATH }}
          asset_name: micronaut-crud-v${{ github.run_number }}.jar
          asset_content_type: application/java-archive
